pipeline {
    agent any
    stages {
    	stage('git-checkout') {
            steps {
                echo 'Checkout from git repo'
                git branch: 'test', url: 'https://github.com/coderboiboi/one2onetool.git'
                }
            }
        stage('build') {
            steps {
                echo 'build project'
                sh '''pwd'''
                sh '''ls -lrt'''
                sh '''deployment/build.sh'''
                }
            }
        stage('test') {
            steps {
                echo 'test project'
                sh '''deployment/test.sh'''
                }
            }
        stage('deploy') {
            steps {
                echo 'deploy project'
                sh '''deployment/deploy.sh'''
                }
            }

        }
    
    emailext body: '', subject: 'Deploy success!', to: 'abc@gmail.com'
}

