pipeline {
    agent any
    stages {
    	stage('git-checkout') {
            steps {
                echo 'Checkout from git repo'
                git 'https://github.com/coderboiboi/one2onetool.git'
                }
            }
        stage('build') {
            steps {
                echo 'build project'
                sh '''build.sh'''
                }
            }
        stage('test') {
            steps {
                echo 'test project'
                sh '''test.sh'''
                }
            }
        stage('deploy') {
            steps {
                echo 'deploy project'
                sh '''deploy.sh'''
                }
            }

    }
}

