pipeline {
    agent any
    stages {
    	stage('git-checkout') {
            steps {
                echo 'Checkout from git repo'
                git 'https://github.com/coderboiboi/one2onetool.git'
                }
            }

    }
}

